// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace Conduit.Persistence.Migrations
{
    public partial class UpdateArticleFavoritesCount : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<int>(
                name: "FavoritesCount",
                table: "Articles",
                nullable: false,
                oldClrType: typeof(bool));
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<bool>(
                name: "FavoritesCount",
                table: "Articles",
                nullable: false,
                oldClrType: typeof(int));
        }
    }
}
